# Generated by Django 3.0.4 on 2020-06-09 15:49

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateTimeField()),
                ('data_pagamento', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.CharField(max_length=255)),
                ('situacao', models.CharField(choices=[('Pago', 'Pago'), ('A pagar', 'A pagar')], default='A pagar', max_length=10)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
