# Generated by Django 3.0.4 on 2020-06-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefinanceiro', '0002_auto_20200609_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaspagar',
            name='data_pagamento',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='data_vencimento',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
