# Generated by Django 3.0.4 on 2020-06-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefinanceiro', '0004_classificacaopagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaspagar',
            name='classificacoes',
            field=models.ManyToManyField(to='controlefinanceiro.ClassificacaoPagar'),
        ),
    ]
