# Generated by Django 3.0.4 on 2020-06-09 21:40

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('controlefinanceiro', '0007_auto_20200609_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_expectativa', models.DateTimeField()),
                ('data_recebimento', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.CharField(max_length=255)),
                ('situacao', models.CharField(choices=[('Recebido', 'Recebido'), ('A receber', 'A receber')], default='Recebido', max_length=10)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
