# Generated by Django 3.0.4 on 2020-06-11 00:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('controlefinanceiro', '0009_contasreceber_classificacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='formaspagamento',
            field=models.ManyToManyField(to='controlefinanceiro.FormaPagamento'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='formaspagamento',
            field=models.ManyToManyField(to='controlefinanceiro.FormaPagamento'),
        ),
    ]
