# Generated by Django 3.0.4 on 2020-06-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefinanceiro', '0010_auto_20200610_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacaopagar',
            name='tipo',
            field=models.CharField(choices=[('pagar', 'pagar'), ('receber', 'receber')], default='pagar', max_length=10),
        ),
    ]
