# Generated by Django 3.0.4 on 2020-06-13 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlefinanceiro', '0011_classificacaopagar_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contaspagar',
            name='classificacoes',
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='classificacoes',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='controlefinanceiro.ClassificacaoPagar'),
        ),
        migrations.RemoveField(
            model_name='contaspagar',
            name='formaspagamento',
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='formaspagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controlefinanceiro.FormaPagamento'),
        ),
        migrations.RemoveField(
            model_name='contasreceber',
            name='classificacoes',
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='classificacoes',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='controlefinanceiro.ClassificacaoPagar'),
        ),
        migrations.RemoveField(
            model_name='contasreceber',
            name='formaspagamento',
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='formaspagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controlefinanceiro.FormaPagamento'),
        ),
    ]
